In [14]:
import numpy as np
a=np.array([5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5])

In [15]:
type(a)

numpy.ndarray

In [16]:
len(a)

6

In [18]:
b=np.array([[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5]])

In [19]:
type(b)

numpy.ndarray

In [20]:
len(b)

2

In [22]:
c=np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [24]:
d=np.zeros(3)
d

array([0., 0., 0.])

In [25]:
e=np.ones(6)
e

array([1., 1., 1., 1., 1., 1.])

In [37]:
# craete an empty with two elements
f=np.empty(2)
f

array([1.19830001e-308, 7.04240981e-021])

In [38]:
g=np.arange(9)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
# with specify range of elements:
h=np.arange(19,30)
h

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
# continue
i=np.arange(3,30,3)
i

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [41]:
# lenierly spaced array
j=np.linspace(0,10,num=5)# give use 5 nums
j

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
import numpy as np
a=np.array([5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5])

In [15]:
type(a)

numpy.ndarray

In [16]:
len(a)

6

In [18]:
b=np.array([[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5]])

In [19]:
type(b)

numpy.ndarray

In [20]:
len(b)

2

In [22]:
c=np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [24]:
d=np.zeros(3)
d

array([0., 0., 0.])

In [25]:
e=np.ones(6)
e

array([1., 1., 1., 1., 1., 1.])

In [37]:
# craete an empty with two elements
f=np.empty(2)
f

array([1.19830001e-308, 7.04240981e-021])

In [38]:
g=np.arange(9)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
# with specify range of elements:
h=np.arange(19,30)
h

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
# continue
i=np.arange(3,30,3)
i

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [41]:
# lenierly spaced array
j=np.linspace(0,10,num=5)# give use 5 nums
j

array([ 0. ,  2.5,  5. ,  7.5, 10. ])